Ursapolly/translation into rus
installero/rubyinstaller.ru pull request #1
Opened 2019-03-20 13:09 UTC by ursapolly

2019-03-25 15:10 UTC, installero requested changes

2019-03-25 15:10 UTC, installero commented on .gitignore
> +.idea
Вот это лишнее

https://gist.github.com/subfuzion/db7f57fff2fb6998a16c

2019-03-25 15:10 UTC, installero commented on Gemfile.lock
> +   ruby 2.3.7p456
А зачем поменяла версию руби?

2019-03-25 15:10 UTC, installero commented on Gemfile.lock
> +   2.0.1
И бандлера?

2019-03-26 06:20 UTC, ursapolly commented on Gemfile.lock
> +   ruby 2.3.7p456
Хм... Не меняла ничего. Складировала, создала ветку, сделала `bundle install` и подняла сервер. В Гемфайле ничего не трогала.

2019-03-26 08:16 UTC, ursapolly commented on .gitignore
> +.idea
Ок, это поправила.

2019-03-26 16:38 UTC, installero commented on Gemfile.lock
> +   ruby 2.3.7p456
Ну так это в `Gemfile.lock` :)

2019-03-26 16:39 UTC, installero commented on .gitignore
> +.idea
Не вижу изменений пока.

2019-03-28 12:22 UTC, installero requested changes

2019-03-28 12:22 UTC, installero commented on .gitignore
> +.token.yml
Перенос строки в конце файла нужно вернуть

2019-03-28 12:38 UTC, ursapolly commented on .gitignore
> +.token.yml
Done

2019-03-28 12:45 UTC, merged